version: '3.7'

secrets:
  db_ini:
    file: './configFiles/db.ini'
  omeka_db_password:
    external: true
  omeka_db_root_password:
    external: true

services:
  db:
    image: 'mysql:5.7'
    environment:
      MYSQL_DATABASE: dbcenieh
      MYSQL_PASSWORD_FILE: /run/secrets/omeka_db_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/omeka_db_root_password
      MYSQL_USER: cenieh
    volumes:
      - 'db:/var/lib/mysql'
    secrets:
      - omeka_db_password
      - omeka_db_root_password
      
  omeka-db-admin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8000:80
    environment:
      - PMA_HOST=db
    depends_on:
      - db    
      
  omeka_app:
    image: gcm1001/omeka_cenieh:latest
    ports:
      - '80:80'
    volumes:
      - 'files:/var/www/html/files'
    secrets:
      - source: db_ini
        target: /var/www/html/db.ini
        uid: '33'
        gid: '33'
        mode: 0440
    depends_on:
      - db
      
volumes:
  db:
  files:
