version: '3.7'

secrets:
  db_ini:
    file: './configFiles/db.ini'
  omeka_db_password:
    external: true
  omeka_db_root_password:
    external: true
  omeka_repo:
    external: true
    
services:
  db:
    image: 'mysql:5.7'
    environment:
      MYSQL_DATABASE: dbcenieh
      MYSQL_PASSWORD_FILE: /run/secrets/omeka_db_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/omeka_db_root_password
      MYSQL_USER: cenieh
    volumes:
      - 'db:/var/lib/mysql'
    secrets:
      - omeka_db_password
      - omeka_db_root_password

  omeka_app:
    image: gcm1001/omeka_cenieh
    ports:
      - '80:80'
    volumes:
      - 'files:/var/www/html/files'
    secrets:
      - source: db_ini
        target: /var/www/html/db.ini
        uid: '33'
        gid: '33'
        mode: 0440
    environment:
      DB_DATABASE: /run/secrets/omeka_db_database
      DB_HOST: /run/secrets/omeka_db_host
      DB_PASSWORD: /run/secrets/omeka_db_password
      DB_USERNAME: /run/secrets/omeka_db_username
    depends_on:
      - db
      
volumes:
  db:
  files:
