apiVersion: apps/v1
kind: Deployment
metadata:
  name: omeka
spec:
  template:
    spec:
      containers:
      - name: omeka
        env:
        - name: DB_HOST
          value: $(MYSQL_SERVICE)
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: omeka-db
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: omeka-db
              key: user-password
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: omeka-db
              key: database
        - name: IMAP_HOST
          valueFrom:
            secretKeyRef:
              name: omeka-imap
              key: host
        - name: IMAP_USERNAME
          valueFrom:
            secretKeyRef:
              name: omeka-imap
              key: username
        - name: IMAP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: omeka-imap
              key: password
        - name: IMAP_PORT
          valueFrom:
            secretKeyRef:
              name: omeka-imap
              key: port
        - name: IMAP_SSL
          valueFrom:
            secretKeyRef:
              name: omeka-imap
              key: ssl
        - name: SNMP_HOST
          valueFrom:
            secretKeyRef:
              name: omeka-snmp
              key: host
        - name: SNMP_USERNAME
          valueFrom:
            secretKeyRef:
              name: omeka-snmp
              key: username
        - name: SNMP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: omeka-snmp
              key: password
        - name: SNMP_PORT
          valueFrom:
            secretKeyRef:
              name: omeka-snmp
              key: port
        - name: SNMP_SSL
          valueFrom:
            secretKeyRef:
              name: omeka-snmp
              key: ssl
        volumeMounts:
        - name: db-config
          mountPath: /var/www/html/db.ini
          subPath: db.ini
        - name: snmp-config
          mountPath: /var/www/html/application/config.ini
          subPath: config.ini
        - name: imap-config
          mountPath: /var/www/html/plugins/AriadnePlusTracking/mail.ini
          subPath: mail.ini
      restartPolicy: Always
      volumes:
        - name: db-config
          configMap:
            name: db-config
        - name: snmp-config
          configMap:
            name: snmp-config
        - name: imap-config
          configMap:
            name: imap-config
      
