apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: omeka
  labels:
    app: omeka
spec:
  selector:
    matchLabels:
      app: omeka
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: omeka
    spec:
      containers:
      - image: gcr.io/ubucenh/gke-omeka:latest
        name: omeka
        ports:
        - containerPort: 80
          name: omeka
