  name: Docker CI/CD
  
  on:
    push:
      branches:
        - develop
      paths-ignore:
        - 'docs/**'
        
  jobs:
      Docker:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v1
          - name: Login
            run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
          - name: Build
            run: docker build -t omeka_cenieh .
          - name: Tags
            run: |
                docker tag omeka_cenieh ${{ secrets.DOCKER_USER }}/omeka_cenieh:${{ github.sha }}
                docker tag omeka_cenieh ${{ secrets.DOCKER_USER }}/omeka_cenieh:latest
          - name: Push
            run: |
                docker push ${{ secrets.DOCKER_USER }}/omeka_cenieh:${{ github.sha }}
                docker push ${{ secrets.DOCKER_USER }}/omeka_cenieh:latest
